---
- name: Start a container with a command
  hosts: 127.0.0.1
  tasks:
    - name: Start the frontend container
      community.docker.docker_container:
        name: frontend
        image: ghcr.io/thomas-mauran/kana-frontend:3bb30af
        published_ports:
          - "80:80"
        env:
          KANAS_BACKEND_SERVICE_HOST : "{{ backend }}"