---
  - name: Stop and disable UFW
    ansible.builtin.systemd:
      name: ufw
      state: stopped
      enabled: no
    become: yes  # Ensures the command is run with elevated privileges
    
  - name: Install rke2 and update the token file
    hosts: 127.0.0.1
    tasks:
      - 
      - name: Install rke2
        ansible.builtin.shell:
          cmd: |
            curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="agent" sh -

        become: yes  # Ensures the command is run with elevated privilegesz
  - name: enable and start the rke2 service
    hosts: 127.0.0.1
    tasks:
      - name: enable and start the rke2 service
        ansible.builtin.systemd:
          name: rke2-agent
          enabled: yes
          state: started
        become: yes  # Ensures the command is run with elevated privileges